<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalidadesSeeder extends Seeder
{
    public function run()
    {
        DB::table('localidades')->insert([
            ['idLocalidad' => 1, 'Desc_Localidad' => 'Posadas', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 2, 'Desc_Localidad' => 'Obera', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 3, 'Desc_Localidad' => 'Apostoles', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 4, 'Desc_Localidad' => 'Ñu Porá', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 5, 'Desc_Localidad' => 'Fachinal', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 6, 'Desc_Localidad' => 'Apóstoles', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 7, 'Desc_Localidad' => 'Bº Estación', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 8, 'Desc_Localidad' => 'San José', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 9, 'Desc_Localidad' => 'Azara', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 10, 'Desc_Localidad' => 'Puerto Azara', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 11, 'Desc_Localidad' => 'Tres Capones', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 12, 'Desc_Localidad' => 'Santa Ana', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 13, 'Desc_Localidad' => 'Candelaria', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 14, 'Desc_Localidad' => 'Profundidad', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 15, 'Desc_Localidad' => 'Cerro Corá', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 16, 'Desc_Localidad' => 'Bonpland', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 17, 'Desc_Localidad' => 'Mártires', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 18, 'Desc_Localidad' => 'Loreto', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 19, 'Desc_Localidad' => 'Leandro N. Alem', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 20, 'Desc_Localidad' => 'Olegario Víctor Andrade', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 21, 'Desc_Localidad' => 'Cerro Azul', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 22, 'Desc_Localidad' => 'Arroyo del Medio', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 23, 'Desc_Localidad' => 'Dos Arroyos', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 24, 'Desc_Localidad' => 'Gobernador López', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 25, 'Desc_Localidad' => 'Caá Yarí', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 26, 'Desc_Localidad' => 'Almafuerte', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 27, 'Desc_Localidad' => 'Concepción de la Sierra', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 28, 'Desc_Localidad' => 'Barra Concepción', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 29, 'Desc_Localidad' => 'Santa María', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 30, 'Desc_Localidad' => 'San Javier', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 31, 'Desc_Localidad' => 'Tacaruaré', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 32, 'Desc_Localidad' => 'Mojón Grande', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 33, 'Desc_Localidad' => 'Florentino Ameghino', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 34, 'Desc_Localidad' => 'Puerto Rosario', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 35, 'Desc_Localidad' => 'San Ignacio', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 36, 'Desc_Localidad' => 'Corpus', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 37, 'Desc_Localidad' => 'Gobernador Roca', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 38, 'Desc_Localidad' => 'Santo Pipó', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 39, 'Desc_Localidad' => 'Hipólito Yrigoyen', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 40, 'Desc_Localidad' => 'General Urquiza', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 41, 'Desc_Localidad' => 'Colonia Polana', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 42, 'Desc_Localidad' => 'Jardín América', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 43, 'Desc_Localidad' => 'Oberá', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 44, 'Desc_Localidad' => 'General Alvear', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 45, 'Desc_Localidad' => 'Colonia Alberdi', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 46, 'Desc_Localidad' => 'Campo Viera', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 47, 'Desc_Localidad' => 'Campo Ramón', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 48, 'Desc_Localidad' => 'Panambí', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 49, 'Desc_Localidad' => 'Los Helechos', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 50, 'Desc_Localidad' => 'Guaraní', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 51, 'Desc_Localidad' => 'San Martín', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 52, 'Desc_Localidad' => 'Puerto Rico', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 53, 'Desc_Localidad' => 'Puerto Leoni', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 54, 'Desc_Localidad' => 'Puerto Mineral', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 55, 'Desc_Localidad' => 'Capioví', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 56, 'Desc_Localidad' => 'Ruiz de Montoya', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 57, 'Desc_Localidad' => 'Garuhapé', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 58, 'Desc_Localidad' => 'El Alcázar', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 59, 'Desc_Localidad' => 'Dos de Mayo', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 60, 'Desc_Localidad' => 'Pueblo Illia', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 61, 'Desc_Localidad' => 'Campo Grande', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 62, 'Desc_Localidad' => 'Aristóbulo del Valle', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 63, 'Desc_Localidad' => 'Alba Posse', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 64, 'Desc_Localidad' => '25 de Mayo', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 65, 'Desc_Localidad' => 'Colonia Aurora', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 66, 'Desc_Localidad' => 'Colonia Alicia', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 67, 'Desc_Localidad' => 'Colonia Aparecida', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 68, 'Desc_Localidad' => 'Montecarlo', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 69, 'Desc_Localidad' => 'Caraguatay', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 70, 'Desc_Localidad' => 'Taruma', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 71, 'Desc_Localidad' => 'Puerto Piray', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 72, 'Desc_Localidad' => 'San Vicente', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 73, 'Desc_Localidad' => 'El Soberbio', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 74, 'Desc_Localidad' => 'Colonia La Nueva', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 75, 'Desc_Localidad' => 'Colonia Monteagudo', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 76, 'Desc_Localidad' => 'Eldorado', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 77, 'Desc_Localidad' => '9 de Julio', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 78, 'Desc_Localidad' => 'Santiago de Liniers', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 79, 'Desc_Localidad' => 'Colonia Victoria', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 80, 'Desc_Localidad' => 'Colonia Delicia', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 81, 'Desc_Localidad' => 'San Pedro', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 82, 'Desc_Localidad' => 'Colonia Paraíso', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 83, 'Desc_Localidad' => 'Tobuna', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 84, 'Desc_Localidad' => 'Esperanza', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 85, 'Desc_Localidad' => 'Wanda', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 86, 'Desc_Localidad' => 'Libertad', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 87, 'Desc_Localidad' => 'Iguazú', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 88, 'Desc_Localidad' => 'Bdo. Irigoyen', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 89, 'Desc_Localidad' => 'San Antonio', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 90, 'Desc_Localidad' => 'Andresito Guacurarí', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 91, 'Desc_Localidad' => 'Villa Lanús', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 92, 'Desc_Localidad' => 'Itaembé', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 93, 'Desc_Localidad' => 'Garupá', 'Provincias_idProvincia' => 1],
            ['idLocalidad' => 94, 'Desc_Localidad' => 'Santa Inés', 'Provincias_idProvincia' => 1],
        ]);
    }
}